{% set name = "dict2xml" %}
{% set version = "1.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dict2xml-{{ version }}.tar.gz
  sha256: 3e4811f4ef7fca86dede6acf382268ff9bc5735a4aa0e21b465f6eb0c4e81732

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - dict2xml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/delfick/python-dict2xml/
  summary: Small utility to convert a python dictionary into an XML string
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/delfick/python-dict2xml/

extra:
  recipe-maintainers:
    - manics
